content:
  - name: dates
    label: Dates
    path: src/lib/content/dates
    type: collection
    filename: >
      "{fields.date.split('T')[0]}.md"
    subfolders: false
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: menu
    label: Menu
    type: file
    path: src/lib/content/menu.md
    fields:
      - name: title
        label: Menu Title
        type: string
        default: Menu
      - name: links
        label: Links
        description: Should be some label/url pairs to generate links
        type: object
        list: true
        fields:
          - name: label
            label: Link Label
            type: string
          - name: url
            label: Link URL
            type: string
