content:

  - name: posts
    label: Posts
    path: src/lib/content/posts
    type: collection
    filename: '{year}-{month}-{day}-{primary}.md'
    subfolders: false
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: menu
    label: Menu
    type: file
    path: src/lib/content/menu.md
    fields:
      - name: links
        label: Links
        description: Should be some label/url pairs to generate links
        type: object
        fields:
          - name: label
            label: Link Label
            type: string
          - name: url
            label: Link URL
            type: string
